### ISSUE TITLE
创建用户接口调用500，入库报错。疑似数据类型问题。

### ISSUE THREAD

**Issue by houziyu** [fastapi-practices/fastapi_sqlalchemy_mysql#10]
创建用户接口调用500。好像是生成的UUID为UUID类型，然后数据库是str类型无法写入导致。
![WX20231120-181148](https://github.com/fastapi-practices/fastapi_sqlalchemy_mysql/assets/17023204/385b0833-33a2-4e77-8746-ce354d75b76f)
![WX20231120-181155](https://github.com/fastapi-practices/fastapi_sqlalchemy_mysql/assets/17023204/7bd07e0c-5420-40e9-baa5-7b03ea450239)

**Comment by houziyu** [comment]
new_user.uuid = str(new_user.uuid) 增加一条 UUID转换str类型就可以写入数据库了。

**Comment by wu-clan** [comment]
此问题当前采用尽可能兼容性修复，您可以查看相关PR.
