### ISSUE TITLE
swagger_login获取TOken时候，插入登录时间报错。

### ISSUE THREAD

**Issue by houziyu** [fastapi-practices/fastapi_sqlalchemy_mysql#14]
![1700558654685](https://github.com/fastapi-practices/fastapi_sqlalchemy_mysql/assets/17023204/cdace9d5-c50e-4331-913f-c3e24b2e393b)

**Comment by houziyu** [comment]
上一级传的是userid。但是update_user_login_time 使用username进行匹配的。

**Comment by wu-clan** [comment]
此问题已修复，请同步至最新分支

**Comment by houziyu** [comment]
![WX20231121-175039](https://github.com/fastapi-practices/fastapi_sqlalchemy_mysql/assets/17023204/50608a22-0a27-4b05-92c5-6f99d2e29e49)

重置密码表单参数错误不应该是password1 和password2 应该是    new_password和 confirm_password

**Comment by wu-clan** [comment]
已修复

此仓库于三周前进行全量重置更新，未经覆盖测试，非常感谢您的宝贵意见，欢迎提出任何问题
