### ISSUE TITLE
验证码登录接口报错

### ISSUE THREAD

**Issue by houziyu** [fastapi-practices/fastapi_sqlalchemy_mysql#18]
![WX20231201-173419](https://github.com/fastapi-practices/fastapi_sqlalchemy_mysql/assets/17023204/f757e4cc-0948-4ddd-97ee-b2c66ad0d4cf)
需要修改成
 if redis_code.lower() != obj.captcha.lower():

**Comment by wu-clan** [comment]
Thanks.
