### ISSUE TITLE
执行最后一步backend/app/main.py报错ModuleNotFoundError: No module named 'backend'

### ISSUE THREAD

**Issue by darkwavekv** [fastapi-practices/fastapi_sqlalchemy_mysql#9]
按照步骤都执行成功了，最后一步命令行里执行python backend/app/main.py报错，找不到backend模块。只能通过在执行文件添加sys绝对路径才能执行成功。
咨询一下还有什么其他方法吗。

**Comment by wu-clan** [comment]
优先查阅：python运行时包的搜索路径

另外两种办法
- PYTHONPATH变量
- xxx.pth文件

**Comment by darkwavekv** [comment]
> 优先查阅：python运行时包的搜索路径
> 
> 另外两种办法
> 
> * PYTHONPATH变量
> * xxx.pth文件

多谢，之前的项目一直都是把执行文件放在顶级目录下，很少用这种结构，感觉当前结构很合理，作为脚手架很好用
